version: '3'

services:
    web_php8:
        build:
            context: ./web_php8
            dockerfile: Dockerfile
        volumes:
            - ./src/phpunit_board:/var/www/html
        ports:
            - "80:80"

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: "Asia/Tokyo"

    php-my-admin:
        image: phpmyadmin/phpmyadmin:5.0
        ports:
            - "8080:80"
        environment:
            MYSQL_USERNAME: user
            MYSQL_ROOT_PASSWORD: pass
            PMA_HOST: db
            PMA_PORT: 3306
